language: c
addons:
  apt:
    packages:
    - curl
branches:
  only:
  - master
install:
- curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
- sudo mv ./luvit /bin/
script:
- cd tests
- luvit main.lua
env:
  global:
  - secure: DVzbFYHJU0nCk8vsPpbTnRCufRr+5EhgzIcIHDlF2udgOsKb2EdmVdjiVdIB0VM6nnP2xwGuza9NSKbSI17oWfdDupllJqTddM4j0tWDwhLUEeq7vb0uLhS/2dJshoJazvr0SxnHOB5QkooQP16meUirOK1dThJJlOY/uR5PhNNkodJbUo93WYmg1SbCmSkOt5WpL2qC4QrxwqUVJuhwCZX5jhJdI4O+hl7bXVX1I/dWHkMXrFZPw5FCd1sRY8IrDzc6nwmBKL2zfcoaKIjSYI1M+S1aniwrjsj+IEqqru9DCuQAXZ7FxF34uFlCtnCNh4+JzPSdPXwq36h32pvYM4aWRq0TSFDDHg2T9sIv7oWpKptP6Wlzl+WTGw8tqsQdn0392lSuLIDXtw5UJtUktCOOzkI6x+Htxe9T0IGiBONzD6Y/aRah9BOauLJvFZovIGCNIbgCfiC2IjD2+sTveCSuYE+i6HN/udqvoV5S+Bm+Zyv2CzKCozdUGfq9SBoHLmhDlUXX8r8LCZtrrNpO9KSZ2WhcUsNCbzWfEK7lGgl9Z6JfmLJ44faj5B3HlGH6ygniWenOLmZIpg96Dt2bIiPKmKgKLu/dzBv2amj6KFVSASQRVGg0AGVVo9JStHkgrAUzzIxgV5csB7PC2+NBDNNrr33NSNKyPOrEmxpbZkA=
  - secure: aJWl84tZ01I+kUhS9J8ic+IU3+al0HLmsD1MuSDoVZgzlrCzoBKX91joRu/LjhOWTbO3EP/hUXYikdONJXwfg7AKFtdemlNQU2zUlzfnOn42f2uN+19Q537+D7HLtKFR1T1J9Bn2rQJqSJVaoOZo3xrHz/APlf8UkVLgvHsLhW3c5MkLkJQd/HzazvN93oX+rUDdwxLZa4S8rMJsBQuQucl/jctUfn0RpayytTL+PaJnD9CiDwIsRIKf5a03YsTz9J2b1yGpW6uuWJTE1mwTV7+Y5kfG6WPgwaya3hW58WA4BQUyxbJfBhgn6GfQU0pO1KiXIVKJl5h5GEtn6iqNyge1JA5J4LhzxnkESWSjB2MPTcbWGWZPkk54vXLfFckM+QVn2si9JI/x6ThEZT0QuLAlCIlO0XlLs+liRvVhRmEBcaVzpPdUOCMONDC86W1DcRQJXzybrZ/x5QVF7mCH5nNJW88/SJamBySEAPzCiejkuw3k+JHRuPXzfnHwCBciYl4G5Qc3N8nPn2iTI+S/aE/Hg2iytGOyaV3tbSY8waHzz5mSSS1CAHEcmjGvfxiA+FKK4jLRFlvo5hfcdyMNG0aZqjQH4lfB8JPsomQup/7NB9SKJp2C0yEW+SVvnV7UKDfIx2ax+HUmNvXMc3fDRzbgjylkaV+zfmNbkVA3VFA=
